### ISSUE TITLE
Markup appears in posting

### ISSUE THREAD

**Issue by jcornelius** [nicdev/job-approval-notification#2]
The message in Slack includes markup around the word "Description".

![screenshot 2018-02-20 14 41 49](https://user-images.githubusercontent.com/366136/36445476-67c20e44-164c-11e8-91e4-3eaf68517e9b.png)

**Comment by nicdev** [comment]
The field is converting HTML to entities, so it's effectively a string, not a tag. It's probably a good idea to specify as much in the jobs form.
